# Generated by Django 4.2.5 on 2023-10-03 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0004_projectsinportfolio'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='projectsinportfolio',
            unique_together={('portfolio', 'project')},
        ),
    ]
